pep8:
    full: true
doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
autodetect: yes
ignore-paths:
    - peachpy/arm
pylint:
    disable:
        - global-statement
        - global-variable-not-assigned
        - old-style-class

